### PR TITLE
Fix todo status changed to UPPERCASE

### PR DESCRIPTION
**Pull request by codeliner**
Since we use the enum lib todo status is stored uppercase in the read model and this breaks the frontend code. 

The PR changes the read model to store lowercase again.

Projection reset is required for existing apps.

Also added an unwrapping mechanism for command dispatch exceptions to the ErrorResponse middleware so that new users get the real exception message back instead of command dispatch failed.

### CODE REVIEW

**Comment by prolic** [comment]
Why not adjust the frontend instead of using strtolower?

**Comment by prolic** [comment]
Also travis failed

**Comment by codeliner** [comment]
Travis fails because composer install no longer works with prefer lowest option.
I'd say we wait until Expressive 3.0 and update prooph-do then to use PSR-15 middlewares.

Regarding frontend change. We can do that but it is more work and the issue is caused by a change in the backend. We broke the contract between backend and frontend and my PR fixes the broken contract ;)

Anyway, I'm closing the PR and wait until expressive 3.0. I'd like to replace the frontend with a react version and can fix the broken contract then.

**Comment by prolic** [comment]
:+1:

**Pull request closed without merging**
