### PR TITLE
requires psr/container

### PR DESCRIPTION
**Pull request by basz**
fix 4 https://github.com/prooph/proophessor-do/pull/113

### CODE REVIEW

**Comment by prolic** [comment]
prooph/service-bus 6.0.x-dev should be without -dev now.

**Comment by basz** [comment]
yes, when I do that locally it still fails...

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for prooph/event-store-bus-bridge 3.0.x-dev -> satisfiable by prooph/event-store-bus-bridge[3.0.x-dev].
    - prooph/event-store-bus-bridge 3.0.x-dev requires prooph/service-bus 6.0.x-dev -> no matching package found.
  Problem 2
    - Installation request for prooph/psr7-middleware 0.4.x-dev -> satisfiable by prooph/psr7-middleware[0.4.x-dev].
    - prooph/psr7-middleware 0.4.x-dev requires prooph/service-bus 6.0.x-dev -> no matching package found.

```

does that mean every dependency that reference prooph/service-bus 6.0.x-dev should be updated?

**Comment by prolic** [comment]
Yes!

Am 17.02.2017 15:11 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by prolic** [comment]
Travis failed. Still -dev in proophessor-do?

**Comment by basz** [comment]
travis needs to be restarted

**Comment by prolic** [comment]
I just did.

**Comment by basz** [comment]
ok I was waiting on the other packages so I could restart myself and forgot...

by the way isn't this what branch aliases are for https://getcomposer.org/doc/articles/aliases.md#branch-alias

**Comment by prolic** [comment]
The branch alias was for develop branch, which has been removed now. We can still create a new one for master though.

**Pull request merged**
