### PR TITLE
Delete history_replay.php

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
With `DEPENDENCIES="--prefer-lowest --prefer-stable"`

Composer update fails with:
```
Problem 1

    - zendframework/zend-expressive 2.0.0 requires fig/http-message-util ^1.1.2 -> satisfiable by fig/http-message-util[1.1.2].

    - zendframework/zend-expressive 2.0.1 requires fig/http-message-util ^1.1.2 -> satisfiable by fig/http-message-util[1.1.2].

    - zendframework/zend-expressive 2.0.2 requires fig/http-message-util ^1.1.2 -> satisfiable by fig/http-message-util[1.1.2].

    - zendframework/zend-expressive 2.0.3 requires fig/http-message-util ^1.1.2 -> satisfiable by fig/http-message-util[1.1.2].

    - Conclusion: don't install fig/http-message-util 1.1.2

    - Installation request for zendframework/zend-expressive ^2.0 -> satisfiable by zendframework/zend-expressive[2.0.0, 2.0.1, 2.0.2, 2.0.3].
```

Can somebody look into this? @codeliner @bweston92

**Comment by bweston92** [comment]
@prolic `composer install --prefer-lowest --prefer-stable` works for me, no idea.

**Comment by bweston92** [comment]
@prolic ok seems I had an old composer, on v1.1 I can install but on 1.5 I can't

**Comment by prolic** [comment]
Thanks @bweston92, can you try to solve this? I am really busy these days.

**Comment by prolic** [comment]
@bweston92 @codeliner can you have a look at this one?

**Comment by bgaleotti** [comment]
@prolic Had the same issue in #149, solved by adding `fig/http-message-util` as dependency in   df7f53d54acbe405c661b6b8b4d8f0d83e2d68e2.

**Comment by gogromat** [comment]
Can someone update the readme on how to replay events since the script is now gone?

**Comment by prolic** [comment]
You reset the projection. That's it. Read the event store docs.

**Comment by gogromat** [comment]
Thanks, I will try reading it. But just to give context, I was following [this](https://github.com/prooph/proophessor-do/blob/master/docs/tutorials/replay_history.md) tutorial.

**Pull request closed without merging**
