### PR TITLE
update to use psr\container

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by prolic** [comment]
Some php cs issues

**Comment by akireikin** [comment]
I'm complete newbie in the project. Trying to figure it out. Maybe my question would be stupid, but it seems, the project got broken after this PR. Everywhere I'm getting something like

```
Argument 1 passed to Prooph\ProophessorDo\Container\App\Action\HomeFactory::__invoke() must be an instance of Psr\Container\ContainerInterface, instance of Zend\ServiceManager\ServiceManager given
```

Zend service manager does't implement `Psr\Container\ContainerInterface`. Moreover there is no "psr/container" dependency in `composer.json` file. Is this PR incomplete or I missed smth?

**Comment by prolic** [comment]
@basz can you take care if it please?

**Comment by basz** [comment]
@akireikin can you try 'composer update'

**Comment by akireikin** [comment]
@basz it works. Thank you! 👍

**Pull request merged**
