### PR TITLE
Just check that json is in the content type.

### PR DESCRIPTION
**Pull request by bweston92**
Just check that json is in the content type allows for vendor specific content types like: `application/vnd+prooph.command+json` https://3v4l.org/6vlV1

### CODE REVIEW

**Comment by prolic** [comment]
We should not change the content type detection, but just remove it instead.

Server should validate request not strict, but give response always as strict as possible. The internet designed like this. We cannot force always perfect clean requests and fail if it's not, the server should be as flexible as possible to allow as much as possible. But send always as strict as possible responses.

Strict validation if request (f.e. content-type) is only needed, when you want to return different responses, based on content-type request.

**Comment by bweston92** [comment]
@prolic updated :)

**Comment by prolic** [comment]
@bweston92 can you submit this PR to the develop branch?

**Comment by codeliner** [comment]
I'm closing this one as our new psr7-middleware is used now instead of the Commanding\API. In psr7-middleware we also do not check the content-type so the issue is covered.

**Pull request closed without merging**
