### PR TITLE
make projector idempotence

### PR DESCRIPTION
**Pull request by basz**
so tables table truncation before event replay becomes optional

### CODE REVIEW

**Comment by prolic** [comment]
@basz when a user was registered or a todo as posted, how can it be, that it will be updated in the projector?

**Comment by basz** [comment]
It's a bit counter intuitive and only useful for event replay.

If you do not truncate the read table (which might be useful in production) but consider it's state incorrect and you are updating the state to the one the event stream brings.

You would have to be careful of other fields not set by the event (those might need to be nullified).

On second thought, perhaps a DELETE statement would be more better suited

**Comment by prolic** [comment]
No, prior to event replaying and recreation of the projection, you need to drop the projection. When replaying projections, you start from scratch.

**Comment by basz** [comment]
don't want to go 'against the flow' or come across as stubborn, but couldn't you decided that per projector? I agree a demo application probably shouldn't do it...

**Comment by prolic** [comment]
I would say no. When replaying the events and recreating the projections, this can also mean, that you changed the whole projection and have a new structure (or fixed bugs). So when you replay the events, you'll get a fresh projection. When you reuse the old projection, this can lead to strange projections.

If you want to keep your projection, then change your event-bus config, so that you don't recreate it (to safe time, or whatever). When you replay your events from scratch, you'll create a new projection, at the first creating there was an empty database, so there is no reason a filled database is there when replaying.

**Pull request closed without merging**
