### PR TITLE
Updated docker docs (php7 image and event store adapter)

### PR DESCRIPTION
**Pull request by rommsen**
After the gitter discussions with @sandrokeil and https://github.com/prooph/proophessor-do/issues/65 I updated the installation instructions for using the repo with docker.  It now uses the new php7 image and explains how to install an event store adapter and phpunit.

I also updated docker-compose.yml with the php7 image.

### CODE REVIEW

**Comment by bweston92** [comment]
LGTM

How-ever I don't think you need to mention we only support two database adapters, maybe is can be re-worded as they can always create/contribute their own.

**Comment by rommsen** [comment]
Honestly, I copied this paragraph from further down the docs. I can change it if you want.

**Comment by bweston92** [comment]
IMHO I just think that making it sound more welcoming for extending/contributions would be better. In multiple places if this was a C&P.

**Comment by prolic** [comment]
We have 3 adapters, flywheel is new
Am 29.02.2016 11:48 schrieb "Bradley Weston" <notifications@github.com>:

**Comment by bweston92** [comment]
@prolic that means the docs where already out of date saying 2.

**Comment by codeliner** [comment]
yeah, the docs are out of date atm but we need to add flywheel adapter support to proophessor-do. This can be done in another PR. @rommsen "develop" branch would be better for the PR. Simple rule:
bugfix -> master, everything else -> develop
However, master as target is ok for your current PR.
 @sandrokeil Can you take a look if we can merge? Oh, we cannot use the php7 image together with MongoDB-Adapter as long as it does not use the new mongo extension, right?

**Comment by prolic** [comment]
Yeah
Am 29.02.2016 12:24 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by rommsen** [comment]
@codeliner yeah thats why I asked in gitter this morning. But most of the last prs were directly against master so i thought it would be ok. 

Without the php7 image it was not possible to install at all because one of ocramius packages depend on it (dont know which cause i am on mobile atm)

**Comment by prolic** [comment]
You can use the php7 image, but you cannot use mongodb adapter with php7
currently

Sascha-Oliver Prolic

2016-02-29 12:36 GMT+00:00 Roman Sachse <notifications@github.com>:

**Comment by codeliner** [comment]
@rommsen hhm, I run proophessor-do on php 5.6. Are you sure a dependency has caused the problem? We need to identify it.

**Comment by rommsen** [comment]
Well... hmm...
I just did a fresh install and everything worked fine. Maybe the docker image itself changed? Honestly I have no clue.
on thursday I definitely had
```
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /app/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 100
```
during
```
docker run --rm -it --volume $(pwd):/app composer/composer:master install --no-dev -o --prefer-dist --ignore-platform-reqs
```
and @sandrokeil  told me: "the ocramius package needs PHP 7 so it doesn't work. Don't worry we have the right Docker image for you with the same behaviour https://github.com/prooph/docker-files/tree/master/composer simply replace composer/composer:master with prooph/composer:7.0"


Sorry for causing all the fuss.

**Comment by rommsen** [comment]
Allright guys I tried to completely start from scratch

I deleted all docker containers and images from my machine (brute force I know)
- docker rm $(docker ps -a -q),
- docker rm -f $(docker ps -a -q) 

I made a fresh clone of this repo
I run docker run --rm -it --volume $(pwd):/app composer/composer:master install --no-dev -o --prefer-dist --ignore-platform-reqs
After downloading the composer images: composer/composer and during composer install I got:

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /app/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 98

**Comment by codeliner** [comment]
@rommsen ok thanks. We'll check the issue. Seems to be a problem with the dependencies.

**Comment by rommsen** [comment]
Ok last comment for today from my side. I was actually planning to implement some of your learning todos :D

Here is a much less destructive way of reproducing the problem:

- delete composer.lock file
- run `docker run --rm -it --volume $(pwd):/app composer/composer:master install --no-dev -o --prefer-dist --ignore-platform-reqs`

Now it tries to pull in ocramius/package-version which causes the given error.

**Comment by sandrokeil** [comment]
@rommsen Thanks for your issue report. There are a number of problems:

1. We can not use the Composer flag `--ignore-platform-reqs` anymore and it's not needed, because I updated the Docker images
1. Some of the dependencies uses the PHP 7 Package of Ocramius, so it's failed in PHP 5.6
1. The Docker images doesn't have support for the mongo PHP ext

It's fixed with the new [PHP Docker](https://hub.docker.com/r/prooph/php/builds/https://hub.docker.com/r/prooph/php/builds/) and [Composer](https://hub.docker.com/r/prooph/composer/builds/) images, please update then your PHP/Composer 5.6 images if the Docker build process has finished. The MongoDB Adapter can not be used with PHP 7, so the installation instructions should have this notice.

Please bring your PR to the develop branch, so we can merge it and then I will add some install instructions, as mentioned earlier.

**Comment by rommsen** [comment]
@sandrokeil ok, hope I havent caused too much trouble. 
I close this in favor of https://github.com/prooph/proophessor-do/pull/67

**Pull request closed without merging**
