### PR TITLE
Prooph v7

### PR DESCRIPTION
**Pull request by prolic**
- Require PHP 7.1
- Update to "prooph/common" : "4.0.x-dev"
- Update to "prooph/event-sourcing" : "5.0.x-dev"
- Update to "prooph/event-store" : "7.0.x-dev"
- Update to "prooph/event-store-bus-bridge" : "3.0.x-dev"
- Update to "prooph/pdo-event-store": "1.0.x-dev"
- Update to "prooph/psr7-middleware": "0.4.x-dev"
- Update to "prooph/service-bus" : "6.0.x-dev"
- Update to "sandrokeil/interop-config" : "^2.0.1"

Compatible with:
- "prooph/pdo-snapshot-store": "1.0-dev"
- "prooph/mongodb-snapshot-store": "1.0-dev"
- "prooph/snapshotter": "2.0-dev"

Uses:
- "prooph/php-cs-fixer-config": "^0.1.1"
- "phpunit/phpunit": "^5.7.3"

New features:
- `bin/todo_projection.php`
- `bin/todo_reminder_projection.php`
- `bin/todo_snapshotter.php`
- `bin/user_projection.php`
- `bin/user_snapshotter.php`

Please follow installation instructions at:

`docs/installation.md`

This PR does not include docker compatibilty.

### CODE REVIEW

**Comment by mablae** [comment]
Maybe it would help new users to completely rely on MySql/MariaDB and remove the postgres references from proophessor-do where possible? 

It should be mention in a dedicated paragraph in Readme that Postgres is possibe, too. But at the current state it just make the whole setup process in `Installation.md` very "cluttered" 

Also the docker setup does not setup postgres containers currently.

**Comment by prolic** [comment]
mariadb is not compatible

**Comment by mablae** [comment]
@prolic Isnt MariaDB and adhoc replacement for MySQL anymore? 

Where is it incompatible? 

Docker Files use only mariadb ATM, so does whole prooph docker images by @sandrokeil

**Comment by prolic** [comment]
Mariadb has no JSON fields

**Comment by prolic** [comment]
I tried to test pdo event store with mariadb, the travis build failed with every mariadb version

**Comment by mablae** [comment]
Okay thx @prolic,

Then I will switch to mysql docker containers? Or postgres? We need a simple way to setup, not let new users have to make such decisions :)

**Comment by prolic** [comment]
Ask @sandrokeil. I never used docker.

**Comment by mablae** [comment]
Mentioning @sandrokeil  twice should be enough :)

I am also somewhat new to docker, but it seems like a good way to make setup as easy as possible.

**Comment by prolic** [comment]
@mablae see: https://github.com/prooph/proophessor-do/pull/97/commits/7237d086ad5874f7b0e33d44e1317e487c78508f

this was missing - maybe we need to update the docker part for that, too?

**Pull request merged**
