### PR TITLE
Consider client timezone for deadline validation

### PR DESCRIPTION
**Pull request by sbacelic**
Should fix issue #40

### CODE REVIEW

**Review by prolic — CHANGES_REQUESTED** [review]
No on server side we want to store it as UTC. That's why the title is "CLIENT" timezone deadline validation.

**Comment by sbacelic** [comment]
Got it. I updated pull req.

**Comment by prolic** [comment]
I think the timezone should come from browser, not from php.ini settings. Maybe I am wrong.

@codeliner?

**Comment by sbacelic** [comment]
Used JS datetime picker is converting deadline to UTC anyway. I'd say store it internally in the UTC, and based on i.e. user's TZ settings (this can be added) render date and time differently.

**Comment by prolic** [comment]
@codeliner can you take a look into this?

**Comment by prolic** [comment]
ping @codeliner

**Comment by codeliner** [comment]
sorry for the delay, I totally missed that issue (sometimes too much is going on on github)

I'm with @prolic The client should send UTC and we take that date and construct the `DateTimeImmutable` with time zone `UTC`.

The date picker in the frontend should show local time but store and send UTC. That's the idea of the ticket

**Pull request closed without merging**
